### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by adri94** [olliw42/ardupilot#2]
Hello 

I am on Pi 4 Manjaro trying to build BetaCopter for my pixhawk4 but I get a "Build failed"

```
Waf: Leaving directory `/home/xxx/BetaPilot/build/Pixhawk4'
Build failed
Traceback (most recent call last):
  File "/home/xxx/BetaPilot/modules/waf/waflib/Task.py", line 338, in process
    ret = self.run()
  File "/home/xxx/BetaPilot/Tools/ardupilotwaf/mavgen.py", line 55, in run
    from pymavlink.generator import mavgen
  File "/home/xxx/BetaPilot/modules/mavlink/pymavlink/generator/mavgen.py", line 26, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
```

**Comment by adri94** [comment]
`I ran into a similar problem using Python code written by someone else. Future is a module that aids in conversion between Python 2 and 3. It was an easy installation for me by doing "pip3 install future"`
